services:

  postgres:
    image: postgres:16-alpine
    container_name: vp-analytics-postgres-ms-metrics
    env_file: .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - vp_analytics_data:/var/lib/postgresql/data

volumes:
  vp_analytics_data: